version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: sales_db
    volumes:
      - ./DDL/create_tables.sql:/docker-entrypoint-initdb.d/init_create_tables.sql
      - ./DML/insert_data.sql:/docker-entrypoint-initdb.d/init_insert.sql
      - ./DML/create_smart.sql:/docker-entrypoint-initdb.d/init_smart.sql






